### ISSUE TITLE
Interface not found

### ISSUE THREAD

**Issue by msimo65** [BekoDesign/versio-php-api#7]
Hi, I'm having trouble with the Versio API. So, I want to try it with your code.
I'm not so familiar with namespaces and I'm getting an error: 
Fatal error: Interface 'BekoDesign\versioAPI\Contracts\IClient' not found in C:\wamp64\www\versio-php-api-master\lib\BekoDesign\versioAPI\Client.php on line 27

I have just a simple test.php in the versio-php-api-master folder:
`<?php

require 'lib/BekoDesign/versioAPI/Client.php';

$client = new Client('myusername','mypassword');

$client->categories()->list();`

What am I doing wrong?

**Comment by msimo65** [comment]
I puzzled some more and came up with this:
`<?php

require __DIR__ . '/vendor/autoload.php';
use BekoDesign\versioAPI\Client;

$client = new Client('myusername','mypassword');

var_dump($client->categories()->list());`

But the output is not what I expected.
I expected an array of categories I made in the resellerportal of Versio.

Could you provide me with some examples of how to use it?

**Comment by beko1997** [comment]
The autoload part is indeed important and the easiest way of using composer packages. Otherwise you will have to manually include all the necessary files. If you haven't already reading the composer documentation is a great starting point to understand more about what composer does and how you can use it:
https://getcomposer.org/doc/01-basic-usage.md#autoloading

For your second part of your question: the documentation for this library can be found here:
https://github.com/BekoDesign/versio-php-api/wiki/Usage#categories

That should provide you with an array of the categories specified in the Versio portal. It has been a while since I last used this library myself, so please let me know if the output is not what you expected.

**Comment by msimo65** [comment]
I got an error at first, but that was because some typo's are in the code.
$response = $client->categories->list();  should be  $response = $client->categories**()**->list();

I got it working now!
One thing though. 
I created a contact with $path = Client::VERSIO_URL_TEST in the Client-construct, but it was actually added in real.

Did I miss something somewhere?

**Comment by beko1997** [comment]
I fixed the typo in the wiki page, thanks for letting me know!

The test path should work like you are describing, please refer the base test class for the setup of the test client:
https://github.com/BekoDesign/versio-php-api/blob/master/tests/BaseTest.php

Can you share the code you use for constructing the client? (Without real credentials of course)

**Comment by msimo65** [comment]
`<?php

require __DIR__ . '/vendor/autoload.php';
use BekoDesign\versioAPI\Client;

$client = new Client('myusername','mypassword');

$response = $client->contacts()->create(array(
		'companyname' => 'Jansen BV', 
		'firstname' => 'J', 
		'surname' => 'Jansen', 
		'email' => 'j.jansen@email.com', 
		'phone' => '0698765432', 
		'street' => 'Dorpsstraat', 
		'number' => '1', 
		'number_addition' => 'A', 
		'zipcode' => '1234 AA', 
		'city' => 'Ons dorp', 
		'country' => 'NL'
	));
if($response->getStatusCode() == 200) {
   $contacts = json_decode($response->getBody()->getContents());
	 var_dump($contacts);
} else {
		//Error
}`

in BaseTest.php it says Client::VERSIO_URL_TEST

**Comment by beko1997** [comment]
Ypu should specify the test url inside the constructor of the client like so:

````php
<?php

require DIR . '/vendor/autoload.php';
use BekoDesign\versioAPI\Client;

$client = new Client('myusername','mypassword', Client::VERSIO_URL_TEST); // Changed

$response = $client->contacts()->create(array(
'companyname' => 'Jansen BV',
'firstname' => 'J',
'surname' => 'Jansen',
'email' => 'j.jansen@email.com',
'phone' => '0698765432',
'street' => 'Dorpsstraat',
'number' => '1',
'number_addition' => 'A',
'zipcode' => '1234 AA',
'city' => 'Ons dorp',
'country' => 'NL'
));
if($response->getStatusCode() == 200) {
$contacts = json_decode($response->getBody()->getContents());
var_dump($contacts);
} else {
//Error
}
````

**Comment by msimo65** [comment]
Hmmm...
Changed it, but still getting the result in the live environment. 

525319     |    J Jansen, Ons Dorp, NL

And I get the statuscode 201, but that is not really a problem.

**Comment by beko1997** [comment]
I've just checked it. And your right, but it seems to be a issue within the Versio API itself. I've tested the same request that the API client makes with Postman. And although it uses  `https://www.versio.nl/testapi/v1/` the contact still gets created.

````yml
POST /testapi/v1/contacts HTTP/1.1
Host: www.versio.nl
Authorization: Basic ****
Content-Type: application/json

{"companyname":"Jansen BV","firstname":"J","surname":"Jansen","email":"j.jansen@email.com","phone":"0698765432","street":"Dorpsstraat","number":"1","number_addition":"A","zipcode":"1234 AA","city":"Ons dorp","country":"NL"}
````

I have submitted a ticket to their support so that they can check on this.

**Comment by msimo65** [comment]
Great! Thanx!

**Comment by beko1997** [comment]
> Het is bij ons bekend dat de test api eigenlijk geen test Api is en elementen doorvoert. Qua prioriteit staat dit op dit moment niet hoog op het lijstje en kan daar geen verandering aan gebracht worden.

Translation:
> It is a known issue, the test API is not really a test API at this moment and . Fixing this is not high on the list due to a low priority and it is not possible to change this. 

The response was marked as spam, but this is the answer I received from their support. A bit strange that they will not address a bug in there own API. You would say they could at least add a note to their documentation 🤷‍♂️. 

For now I will add a note to this repository. It might help if people with the same problem report this to the support team of Versio. It might help them with finding the edit button for the priority.

**Comment by BertKooij** [comment]
I will close this issue for now, since it is not really an issue for this library. If there is any more information you can reopen the issue.
